import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { useQuery } from 'react-query';
import { useState } from 'react';

const wasm = import('../build/next_app_with_wasm');

const Home = () => {
  const { data: resolvedWasm } = useQuery('wasm', async () => await wasm);

  const [number, setNumber] = useState<number>(0);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={styles.description}>
          <input
            type="number"
            onChange={(event) => setNumber(Number(event.target.value))}
          />
          <div>5 plus {number} equals {resolvedWasm?.add5(number)}</div>
        </p>
      </main>
    </div>
  );
};

export default Home;
